site: "YouPAC: the Youth Political Action Committee"
baseurl: ""
url: https://youpac.org
permalink: /:title/
collections:
  posts:
    output: true
    permalink: /blog/:title
plugins:
  - jekyll-sitemap
