site: "YouPAC: the Youth Political Action Committee"
baseurl: "/youpac2"
url: youpac.org
permalink: /:title/
collections:
  posts:
    output: true
    permalink: /blog/:title
plugins:
  - jekyll-sitemap
